import os
from typing import Dict, Any, List

class IncidentReporter:
    """
    Generates professional executive and technical Incident Response (IR) reports
    in Markdown format based on live host triage and IOC scan results.
    """

    def __init__(self, output_dir: str = "output"):
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir, exist_ok=True)

    def generate_markdown_report(self, triage_data: Dict[str, Any], ioc_hits: List[Dict[str, Any]]) -> str:
        sys_info = triage_data.get("system_info", {})
        hostname = sys_info.get("hostname", "Unknown")
        timestamp = sys_info.get("timestamp", "Unknown")

        severity_level = "LOW"
        if any(h.get("severity") == "CRITICAL" for h in ioc_hits):
            severity_level = "CRITICAL"
        elif any(h.get("severity") == "HIGH" for h in ioc_hits):
            severity_level = "HIGH"

        report_lines = [
            f"# 🛡️ Mjolnir Incident Response Report",
            f"",
            f"**Generated by:** Mjolnir IR Automation Engine",
            f"**Timestamp:** {timestamp}",
            f"**Target Hostname:** `{hostname}`",
            f"**Overall Incident Severity:** `{severity_level}`",
            f"",
            f"---",
            f"",
            f"## 1. Executive Summary",
            f"Automated host triage was executed on `{hostname}` running `{sys_info.get('os')} {sys_info.get('os_release')}`. ",
            f"The investigation analyzed `{triage_data.get('processes_count', 0)}` running processes and active network sockets against threat intelligence IOC databases.",
            f"",
            f"**Total IOC Hits Detected:** `{len(ioc_hits)}`",
            f"",
            f"---",
            f"",
            f"## 2. Indicators of Compromise (IOC) Findings",
        ]

        if ioc_hits:
            for hit in ioc_hits:
                report_lines.extend([
                    f"- **[SEVERITY: {hit.get('severity')}]** `{hit.get('type')}`",
                    f"  - **Indicator:** `{hit.get('indicator')}`",
                    f"  - **Details:** {hit.get('details')}",
                ])
        else:
            report_lines.append("✅ No known IOCs or suspicious signatures detected in active memory or sockets.")

        report_lines.extend([
            f"",
            f"---",
            f"",
            f"## 3. Host System Telemetry",
            f"- **OS:** `{sys_info.get('os')} {sys_info.get('os_version')}`",
            f"- **Architecture:** `{sys_info.get('architecture')}`",
            f"- **Processor:** `{sys_info.get('processor')}`",
            f"- **Total Active Processes:** `{triage_data.get('processes_count')}`",
            f"- **Total Network Connections:** `{len(triage_data.get('network_connections', []))}`",
            f"",
            f"---",
            f"",
            f"## 4. Recommended Remediation Playbook",
        ])

        if severity_level in ["HIGH", "CRITICAL"]:
            report_lines.extend([
                f"1. **Isolate Host:** Immediately disconnect `{hostname}` from the corporate network to prevent lateral movement.",
                f"2. **Terminate Processes:** Terminate any malicious PIDs identified in the IOC findings.",
                f"3. **Acquire Memory Dump:** Export full RAM dump for deeper digital forensics and timeline reconstruction.",
                f"4. **Credential Rotation:** Force password resets for all privileged accounts active on this host."
            ])
        else:
            report_lines.extend([
                f"1. **Monitor:** Continue passive logging and monitoring via Heimdall SIEM.",
                f"2. **Patch Management:** Ensure system patches and EDR agents are fully up to date."
            ])

        report_content = "\n".join(report_lines)
        
        # Save to output file (Markdown)
        filename = f"Incident_Report_{hostname}_{timestamp.replace(':', '-').replace(' ', '_')}.md"
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_content)

        # Also generate Executive HTML Report (PDF-ready via print stylesheet)
        self.generate_html_report(triage_data, ioc_hits)

        return filepath

    def generate_html_report(self, triage_data: Dict[str, Any], ioc_hits: List[Dict[str, Any]]) -> str:
        sys_info = triage_data.get("system_info", {})
        hostname = sys_info.get("hostname", "Unknown")
        timestamp = sys_info.get("timestamp", "Unknown")

        severity_level = "LOW"
        if any(h.get("severity") == "CRITICAL" for h in ioc_hits):
            severity_level = "CRITICAL"
        elif any(h.get("severity") == "HIGH" for h in ioc_hits):
            severity_level = "HIGH"

        sev_color = "#22c55e" if severity_level == "LOW" else ("#f59e0b" if severity_level == "HIGH" else "#ef4444")

        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mjolnir Incident Report - {hostname}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #000; color: #f5f5f7; margin: 0; padding: 40px; }}
        .container {{ max-width: 900px; margin: auto; background: #161618; border: 1px solid rgba(255,255,255,0.1); border-radius: 20px; padding: 40px; box-shadow: 0 20px 40px rgba(0,0,0,0.8); }}
        h1 {{ font-size: 24px; color: #fff; border-bottom: 1px solid #333; padding-bottom: 15px; }}
        h2 {{ font-size: 18px; color: #38bdf8; margin-top: 30px; }}
        .badge {{ display: inline-block; padding: 6px 14px; border-radius: 20px; font-weight: bold; background: {sev_color}22; color: {sev_color}; border: 1px solid {sev_color}44; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
        th, td {{ padding: 10px 14px; text-align: left; border-bottom: 1px solid #2c2c2e; font-size: 13px; font-family: monospace; }}
        th {{ color: #94a3b8; }}
        .footer {{ margin-top: 40px; font-size: 11px; color: #6b7280; text-align: center; border-top: 1px solid #222; padding-top: 20px; }}
        @media print {{ body {{ background: #fff; color: #000; }} .container {{ background: #fff; border: none; box-shadow: none; }} }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🛡️ Mjolnir Incident Response Executive Report</h1>
        <p><strong>Generated by:</strong> Asgard Mjolnir IR Automation Engine</p>
        <p><strong>Timestamp:</strong> {timestamp}</p>
        <p><strong>Target Hostname:</strong> <code>{hostname}</code></p>
        <p><strong>Severity:</strong> <span class="badge">{severity_level}</span></p>

        <h2>1. Executive Summary</h2>
        <p>Automated host triage executed on <code>{hostname}</code> running <code>{sys_info.get('os')} {sys_info.get('os_release')}</code>. Analyzed <code>{triage_data.get('processes_count', 0)}</code> running processes against threat intelligence databases.</p>
        <p><strong>Total IOC Hits:</strong> {len(ioc_hits)}</p>

        <h2>2. IOC Findings</h2>
"""
        if ioc_hits:
            html_content += """<table><tr><th>Type</th><th>Indicator</th><th>Severity</th><th>Details</th></tr>"""
            for h in ioc_hits:
                html_content += f"<tr><td>{h.get('type')}</td><td><code>{h.get('indicator')}</code></td><td><span style='color:{sev_color}'>{h.get('severity')}</span></td><td>{h.get('details')}</td></tr>"
            html_content += "</table>"
        else:
            html_content += "<p>✅ No known IOCs or suspicious signatures detected in active memory or sockets.</p>"

        html_content += f"""
        <h2>3. Host Telemetry</h2>
        <ul>
            <li><strong>OS:</strong> {sys_info.get('os')} {sys_info.get('os_version')}</li>
            <li><strong>Architecture:</strong> {sys_info.get('architecture')}</li>
            <li><strong>Active Processes:</strong> {triage_data.get('processes_count')}</li>
            <li><strong>Network Connections:</strong> {len(triage_data.get('network_connections', []))}</li>
        </ul>

        <h2>4. Remediation Playbook</h2>
        <ol>
            {"<li><strong>Isolate Host:</strong> Disconnect " + hostname + " from network.</li>" if severity_level in ["HIGH", "CRITICAL"] else "<li><strong>Monitor:</strong> Continue passive monitoring via Heimdall SIEM.</li>"}
            <li><strong>Terminate Processes:</strong> Kill malicious PIDs if identified.</li>
            <li><strong>Memory Dump:</strong> Export full RAM dump for forensics.</li>
        </ol>

        <div class="footer">Asgard Cybersecurity Suite • Mjolnir IR Automation v6.0</div>
    </div>
</body>
</html>
"""
        filename = f"Incident_Report_{hostname}_{timestamp.replace(':', '-').replace(' ', '_')}.html"
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html_content)
        return filepath
