import os
from typing import Dict, Any, List

class IncidentReporter:
    """
    Generates professional executive and technical Incident Response (IR) reports
    in Markdown format based on live host triage and IOC scan results.
    """

    def __init__(self, output_dir: str = "output"):
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir, exist_ok=True)

    def generate_markdown_report(self, triage_data: Dict[str, Any], ioc_hits: List[Dict[str, Any]]) -> str:
        sys_info = triage_data.get("system_info", {})
        hostname = sys_info.get("hostname", "Unknown")
        timestamp = sys_info.get("timestamp", "Unknown")

        severity_level = "LOW"
        if any(h.get("severity") == "CRITICAL" for h in ioc_hits):
            severity_level = "CRITICAL"
        elif any(h.get("severity") == "HIGH" for h in ioc_hits):
            severity_level = "HIGH"

        report_lines = [
            f"# 🛡️ Mjolnir Incident Response Report",
            f"",
            f"**Generated by:** Mjolnir IR Automation Engine",
            f"**Timestamp:** {timestamp}",
            f"**Target Hostname:** `{hostname}`",
            f"**Overall Incident Severity:** `{severity_level}`",
            f"",
            f"---",
            f"",
            f"## 1. Executive Summary",
            f"Automated host triage was executed on `{hostname}` running `{sys_info.get('os')} {sys_info.get('os_release')}`. ",
            f"The investigation analyzed `{triage_data.get('processes_count', 0)}` running processes and active network sockets against threat intelligence IOC databases.",
            f"",
            f"**Total IOC Hits Detected:** `{len(ioc_hits)}`",
            f"",
            f"---",
            f"",
            f"## 2. Indicators of Compromise (IOC) Findings",
        ]

        if ioc_hits:
            for hit in ioc_hits:
                report_lines.extend([
                    f"- **[SEVERITY: {hit.get('severity')}]** `{hit.get('type')}`",
                    f"  - **Indicator:** `{hit.get('indicator')}`",
                    f"  - **Details:** {hit.get('details')}",
                ])
        else:
            report_lines.append("✅ No known IOCs or suspicious signatures detected in active memory or sockets.")

        report_lines.extend([
            f"",
            f"---",
            f"",
            f"## 3. Host System Telemetry",
            f"- **OS:** `{sys_info.get('os')} {sys_info.get('os_version')}`",
            f"- **Architecture:** `{sys_info.get('architecture')}`",
            f"- **Processor:** `{sys_info.get('processor')}`",
            f"- **Total Active Processes:** `{triage_data.get('processes_count')}`",
            f"- **Total Network Connections:** `{len(triage_data.get('network_connections', []))}`",
            f"",
            f"---",
            f"",
            f"## 4. Recommended Remediation Playbook",
        ])

        if severity_level in ["HIGH", "CRITICAL"]:
            report_lines.extend([
                f"1. **Isolate Host:** Immediately disconnect `{hostname}` from the corporate network to prevent lateral movement.",
                f"2. **Terminate Processes:** Terminate any malicious PIDs identified in the IOC findings.",
                f"3. **Acquire Memory Dump:** Export full RAM dump for deeper digital forensics and timeline reconstruction.",
                f"4. **Credential Rotation:** Force password resets for all privileged accounts active on this host."
            ])
        else:
            report_lines.extend([
                f"1. **Monitor:** Continue passive logging and monitoring via Heimdall SIEM.",
                f"2. **Patch Management:** Ensure system patches and EDR agents are fully up to date."
            ])

        report_content = "\n".join(report_lines)
        
        # Save to output file
        filename = f"Incident_Report_{hostname}_{timestamp.replace(':', '-').replace(' ', '_')}.md"
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_content)

        return filepath
